### PR TITLE
feat: Support S/MIME group certificates

### PR DESCRIPTION
**Pull request by albanbruder**
With this MR, the pki-rest-interface now supports listing/issuing and revoking S/MIME certificates for emails other than the user's primary email.

The user's access token is expected to have a custom claim in the following format

```json
{
  "smime_additional_emails": ["groupa@example.org", "groupb@example.org"]
}
```

If the claim is missing, the user's primary email is the only email available for listing/issuing etc.

Listing certificates by email is supported by the `email` query parameter on the `/smime/` endpoint. Requesting a certificate for a different email address can be done by setting the emailAddress subject in the CSR:

```bash
openssl req -new -newkey rsa:4096 -nodes \
            -out Alban_Bruder.csr -keyout Alban_Bruder.key \
            -subj /emailAddress=alban.bruder@uni-weimar.de/
```

The new API is backward compatible: If no email query parameter is provided, or the CSR does not have an emailAddress subject, the user's primary email will be used.

TODO for future PR:
> Currently, the revocation endpoint has to fetch all certificates for all emails to verify that a user is authorised to revoke the certificate with the given serial number. If the PKI service had an endpoint to download/collect a certificate by serial number, we could improve the performance of this endpoint. (will create an issue for that)

### CODE REVIEW

**Comment by fritterhoff** [comment]
Looks good to me. Sadly I caused some conflicts. Would you mind to resolve them? :)

**Comment by albanbruder** [comment]
Sure. Should be fixed now.

**Comment by fritterhoff** [comment]
Grrr... I was to quick updating the depdencies :(

**Comment by albanbruder** [comment]
What is the problem? Do you see any conflicts that I don't? I have merged the relevant changes in the go.mod file into the feature branch.

**Comment by fritterhoff** [comment]
Never mind. Was a ui/caching bug.

**Pull request merged**
